from __future__ import annotations

import hashlib

import numpy as np

import dominion_v2_py as dz


KINGDOM = [
    "Sentry",
    "Library",
    "Throne Room",
    "Bandit",
    "Witch",
    "Moat",
    "Village",
    "Smithy",
    "Market",
    "Remodel",
]


# Snapshots generated by the pre-versioning encoder. These cover the opening
# and three real decision states, and protect v1's byte-level checkpoint ABI.
V1_GOLDEN_SHA256 = [
    (
        "9dda25cd8d1c079daef713cac19258f6504feb0826f252a1f3727b0c2532912e",
        "92588fbf7587098c33981e4656a39e5693b7162594ba2914faeaaa417a828e71",
    ),
    (
        "ffcc5e527f036a02bc069efec45292adccb9b7251cfb47a8e751a22523532b73",
        "e93da2722e5f3d8c53c463181847fa55f2c97e5409a7348a68c74561b308164e",
    ),
    (
        "24912e8f2a7ac6b6934da4cd549167bcbbd554fa70894d38bc9579a2b33fccf4",
        "5792e6d175b5e2854df97673763dbf3be8ece52198d2e45edac742fc850b7229",
    ),
    (
        "b00eae0c3aea8525b7df508f75fc5548c1e9f316987637e623a0f6e4e1d8f7fb",
        "cd70d148c6dfba508fb396f002f16b9a834bb209db3eb4359bd59686888eadce",
    ),
]


def _sha256(obs: np.ndarray) -> str:
    return hashlib.sha256(obs.tobytes()).hexdigest()


def test_v1_default_encoding_matches_pre_versioning_golden_snapshots() -> None:
    game = dz.new_game(dz.Setup(players=2, kingdom=KINGDOM), 0xE4C00001)
    for expected_player0, expected_player1 in V1_GOLDEN_SHA256:
        default0 = game.encode(0)
        default1 = game.encode(1)
        explicit0 = game.encode(0, 1)
        explicit1 = game.encode(1, 1)
        assert default0.shape == (dz.OBS_SIZE_V1,)
        assert default1.shape == (dz.OBS_SIZE_V1,)
        np.testing.assert_array_equal(default0, explicit0)
        np.testing.assert_array_equal(default1, explicit1)
        assert _sha256(default0) == expected_player0
        assert _sha256(default1) == expected_player1
        legal = np.flatnonzero(game.legal_mask())
        assert legal.size > 0
        game.step(int(legal[0]))


def test_v2_game_and_runner_version_selection() -> None:
    assert dz.OBS_VERSION == 1
    assert dz.OBS_SIZE == dz.OBS_SIZE_V1 == 1141
    assert dz.OBS_SIZE_V2 == 1717
    assert dz.OBS_SIZE_V3 == 1788
    assert dz.obs_size_for(1) == dz.OBS_SIZE_V1
    assert dz.obs_size_for(2) == dz.OBS_SIZE_V2
    assert dz.obs_size_for(3) == dz.OBS_SIZE_V3

    game = dz.new_game(dz.Setup(players=2, kingdom=KINGDOM), 0xE4C00002)
    obs = game.encode(0, 2)
    assert obs.shape == (dz.OBS_SIZE_V2,)
    assert obs[0] == 2.0
    assert obs[1] == float(dz.OBS_SIZE_V2)

    obs_v3 = game.encode(0, 3)
    assert obs_v3.shape == (dz.OBS_SIZE_V3,)
    assert obs_v3[0] == 3.0
    assert obs_v3[1] == float(dz.OBS_SIZE_V3)
    np.testing.assert_array_equal(obs_v3[2 : dz.OBS_SIZE_V2], obs[2:])

    config = dz.SelfPlayConfig(
        n_games=2,
        sims_per_move=2,
        max_batch=4,
        seed=0xE4C00003,
        kingdom_mode=dz.SelfPlayKingdomMode.Fixed,
        kingdom=KINGDOM,
        dirichlet_frac=0.0,
        obs_version=2,
    )
    assert config.obs_version == 2
    runner = dz.SelfPlayRunner(config)
    leaves, masks = runner.collect_leaves(config.max_batch)
    assert leaves.shape == (masks.shape[0], dz.OBS_SIZE_V2)
    assert np.all(leaves[:, 0] == 2.0)
    if leaves.shape[0]:
        runner.provide_evaluations(
            np.zeros((leaves.shape[0],), dtype=np.float32),
            np.zeros((leaves.shape[0], dz.ACTION_SPACE_SIZE), dtype=np.float32),
        )

    config_v3 = dz.SelfPlayConfig(
        n_games=2,
        sims_per_move=2,
        max_batch=4,
        seed=0xE4C00005,
        kingdom_mode=dz.SelfPlayKingdomMode.Fixed,
        kingdom=KINGDOM,
        dirichlet_frac=0.0,
        obs_version=3,
    )
    runner_v3 = dz.SelfPlayRunner(config_v3)
    leaves_v3, masks_v3 = runner_v3.collect_leaves(config_v3.max_batch)
    assert leaves_v3.shape == (masks_v3.shape[0], dz.OBS_SIZE_V3)
    assert np.all(leaves_v3[:, 0] == 3.0)
    if leaves_v3.shape[0]:
        runner_v3.provide_evaluations(
            np.zeros((leaves_v3.shape[0],), dtype=np.float32),
            np.zeros((leaves_v3.shape[0], dz.ACTION_SPACE_SIZE), dtype=np.float32),
        )

    searcher = dz.DecisionSearcher(
        game,
        0,
        {"sims": 2, "c_puct": 1.25, "determinizations": 1, "seed": 0xE4C00004, "obs_version": 2},
    )
    leaves, masks = searcher.collect_leaves()
    assert leaves.shape == (masks.shape[0], dz.OBS_SIZE_V2)
    assert np.all(leaves[:, 0] == 2.0)

    searcher_v3 = dz.DecisionSearcher(
        game,
        0,
        {"sims": 2, "c_puct": 1.25, "determinizations": 1, "seed": 0xE4C00006, "obs_version": 3},
    )
    leaves_v3, masks_v3 = searcher_v3.collect_leaves()
    assert leaves_v3.shape == (masks_v3.shape[0], dz.OBS_SIZE_V3)
    assert np.all(leaves_v3[:, 0] == 3.0)
