"""Dominion card wire ordinals from web client bundle version 2.2.8.

Regenerate this table after a client update by downloading the matching main
bundle and extracting, in source order, every
SYMBOL:new CardName("Display name", ...) constructor. Verify the constructor
count and stable base-card spot checks before replacing CARD_TABLE. Symbols
are retained because bundle 2.2.8 contains thirteen distinct reserved slots
whose common display name is "unused".
"""

from __future__ import annotations

from enum import IntEnum


CARD_TABLE: tuple[tuple[str, str], ...] = (
    ("BACK", "Back"),
    ("CURSE", "Curse"),
    ("COPPER", "Copper"),
    ("SILVER", "Silver"),
    ("GOLD", "Gold"),
    ("ESTATE", "Estate"),
    ("DUCHY", "Duchy"),
    ("PROVINCE", "Province"),
    ("ARTISAN", "Artisan"),
    ("BANDIT", "Bandit"),
    ("BUREAUCRAT", "Bureaucrat"),
    ("CELLAR", "Cellar"),
    ("CHAPEL", "Chapel"),
    ("COUNCIL_ROOM", "Council Room"),
    ("FESTIVAL", "Festival"),
    ("GARDENS", "Gardens"),
    ("HARBINGER", "Harbinger"),
    ("LABORATORY", "Laboratory"),
    ("LIBRARY", "Library"),
    ("MARKET", "Market"),
    ("MERCHANT", "Merchant"),
    ("MILITIA", "Militia"),
    ("MINE", "Mine"),
    ("MOAT", "Moat"),
    ("MONEYLENDER", "Moneylender"),
    ("POACHER", "Poacher"),
    ("REMODEL", "Remodel"),
    ("SENTRY", "Sentry"),
    ("SMITHY", "Smithy"),
    ("THRONE_ROOM", "Throne Room"),
    ("VASSAL", "Vassal"),
    ("VILLAGE", "Village"),
    ("WITCH", "Witch"),
    ("WORKSHOP", "Workshop"),
    ("COURTYARD", "Courtyard"),
    ("CONSPIRATOR", "Conspirator"),
    ("COURTIER", "Courtier"),
    ("BARON", "Baron"),
    ("BRIDGE", "Bridge"),
    ("DIPLOMAT", "Diplomat"),
    ("DUKE", "Duke"),
    ("FARM", "Farm"),
    ("NOBLES", "Nobles"),
    ("IRONWORKS", "Ironworks"),
    ("LURKER", "Lurker"),
    ("MASQUERADE", "Masquerade"),
    ("MILL", "Mill"),
    ("MINING_VILLAGE", "Mining Village"),
    ("MINION", "Minion"),
    ("PATROL", "Patrol"),
    ("PAWN", "Pawn"),
    ("REPLACE", "Replace"),
    ("SECRET_PASSAGE", "Secret Passage"),
    ("SHANTY_TOWN", "Shanty Town"),
    ("STEWARD", "Steward"),
    ("SWINDLER", "Swindler"),
    ("TORTURER", "Torturer"),
    ("TRADING_POST", "Trading Post"),
    ("UPGRADE", "Upgrade"),
    ("WISHING_WELL", "Wishing Well"),
    ("AMBASSADOR", "Ambassador"),
    ("BAZAAR", "Bazaar"),
    ("CARAVAN", "Caravan"),
    ("CUTPURSE", "Cutpurse"),
    ("EMBARGO", "Embargo"),
    ("EXPLORER", "Explorer"),
    ("FISHING_VILLAGE", "Fishing Village"),
    ("GHOST_SHIP", "Ghost Ship"),
    ("HAVEN", "Haven"),
    ("ISLAND", "Island"),
    ("LIGHTHOUSE", "Lighthouse"),
    ("LOOKOUT", "Lookout"),
    ("MERCHANT_SHIP", "Merchant Ship"),
    ("NATIVE_VILLAGE", "Native Village"),
    ("NAVIGATOR", "Navigator"),
    ("OUTPOST", "Outpost"),
    ("PEARL_DIVER", "Pearl Diver"),
    ("PIRATE_SHIP", "Pirate Ship"),
    ("SALVAGER", "Salvager"),
    ("SEA_HAG", "Sea Hag"),
    ("SMUGGLERS", "Smugglers"),
    ("TACTICIAN", "Tactician"),
    ("TREASURE_MAP", "Treasure Map"),
    ("TREASURY", "Treasury"),
    ("WAREHOUSE", "Warehouse"),
    ("WHARF", "Wharf"),
    ("ALCHEMIST", "Alchemist"),
    ("APOTHECARY", "Apothecary"),
    ("APPRENTICE", "Apprentice"),
    ("FAMILIAR", "Familiar"),
    ("GOLEM", "Golem"),
    ("HERBALIST", "Herbalist"),
    ("PHILOSOPHERS_STONE", "Philosophers Stone"),
    ("POSSESSION", "Possession"),
    ("POTION", "Potion"),
    ("SCRYING_POOL", "Scrying Pool"),
    ("TRANSMUTE", "Transmute"),
    ("UNIVERSITY", "University"),
    ("VINEYARD", "Vineyard"),
    ("BANK", "Bank"),
    ("BISHOP", "Bishop"),
    ("COLONY", "Colony"),
    ("CONTRABAND", "Contraband"),
    ("COUNTING_HOUSE", "Counting House"),
    ("CITY", "City"),
    ("EXPAND", "Expand"),
    ("FORGE", "Forge"),
    ("GRAND_MARKET", "Grand Market"),
    ("GOONS", "Goons"),
    ("HOARD", "Hoard"),
    ("KINGS_COURT", "Kings Court"),
    ("LOAN", "Loan"),
    ("MINT", "Mint"),
    ("MONUMENT", "Monument"),
    ("MOUNTEBANK", "Mountebank"),
    ("PEDDLER", "Peddler"),
    ("PLATINUM", "Platinum"),
    ("QUARRY", "Quarry"),
    ("RABBLE", "Rabble"),
    ("ROYAL_SEAL", "Royal Seal"),
    ("TALISMAN", "Talisman"),
    ("TRADE_ROUTE", "Trade Route"),
    ("VAULT", "Vault"),
    ("VENTURE", "Venture"),
    ("WATCHTOWER", "Watchtower"),
    ("WORKERS_VILLAGE", "Workers Village"),
    ("PRIZE_PILE", "Prize Pile"),
    ("BAG_OF_GOLD", "Bag Of Gold"),
    ("DIADEM", "Diadem"),
    ("FAIRGROUNDS", "Fairgrounds"),
    ("FARMING_VILLAGE", "Farming Village"),
    ("FOLLOWERS", "Followers"),
    ("FORTUNE_TELLER", "Fortune Teller"),
    ("HAMLET", "Hamlet"),
    ("HARVEST", "Harvest"),
    ("HORSE_TRADERS", "Horse Traders"),
    ("HORN_OF_PLENTY", "Horn Of Plenty"),
    ("HUNTING_PARTY", "Hunting Party"),
    ("JESTER", "Jester"),
    ("MENAGERIE", "Menagerie"),
    ("PRINCESS", "Princess"),
    ("REMAKE", "Remake"),
    ("TOURNAMENT", "Tournament"),
    ("TRUSTY_STEED", "Trusty Steed"),
    ("YOUNG_WITCH", "Young Witch"),
    ("BORDER_VILLAGE", "Border Village"),
    ("CACHE", "Cache"),
    ("CARTOGRAPHER", "Cartographer"),
    ("CROSSROADS", "Crossroads"),
    ("DEVELOP", "Develop"),
    ("DUCHESS", "Duchess"),
    ("EMBASSY", "Embassy"),
    ("FARMLAND", "Farmland"),
    ("FOOLS_GOLD", "Fools Gold"),
    ("HAGGLER", "Haggler"),
    ("HIGHWAY", "Highway"),
    ("ILL_GOTTEN_GAINS", "Ill Gotten Gains"),
    ("INN", "Inn"),
    ("JACK_OF_ALL_TRADES", "Jack Of All Trades"),
    ("MANDARIN", "Mandarin"),
    ("NOBLE_BRIGAND", "Noble Brigand"),
    ("NOMAD_CAMP", "Nomad Camp"),
    ("OASIS", "Oasis"),
    ("ORACLE", "Oracle"),
    ("MARGRAVE", "Margrave"),
    ("SCHEME", "Scheme"),
    ("SILK_ROAD", "Silk Road"),
    ("SPICE_MERCHANT", "Spice Merchant"),
    ("STABLES", "Stables"),
    ("TRADER", "Trader"),
    ("TUNNEL", "Tunnel"),
    ("RUIN_PILE", "Ruin Pile"),
    ("KNIGHTS", "Knights"),
    ("ABANDONED_MINE", "Abandoned Mine"),
    ("ALTAR", "Altar"),
    ("ARMORY", "Armory"),
    ("BAND_OF_MISFITS", "Band Of Misfits"),
    ("BANDIT_CAMP", "Bandit Camp"),
    ("BEGGAR", "Beggar"),
    ("CATACOMBS", "Catacombs"),
    ("COUNT", "Count"),
    ("COUNTERFEIT", "Counterfeit"),
    ("CULTIST", "Cultist"),
    ("DAME_ANNA", "Dame Anna"),
    ("DAME_JOSEPHINE", "Dame Josephine"),
    ("DAME_MOLLY", "Dame Molly"),
    ("DAME_NATALIE", "Dame Natalie"),
    ("DAME_SYLVIA", "Dame Sylvia"),
    ("DEATH_CART", "Death Cart"),
    ("FEODUM", "Feodum"),
    ("FORAGER", "Forager"),
    ("FORTRESS", "Fortress"),
    ("GRAVEROBBER", "Graverobber"),
    ("HERMIT", "Hermit"),
    ("HOVEL", "Hovel"),
    ("HUNTING_GROUNDS", "Hunting Grounds"),
    ("IRONMONGER", "Ironmonger"),
    ("JUNK_DEALER", "Junk Dealer"),
    ("MADMAN", "Madman"),
    ("MARKET_SQUARE", "Market Square"),
    ("MARAUDER", "Marauder"),
    ("MERCENARY", "Mercenary"),
    ("MYSTIC", "Mystic"),
    ("NECROPOLIS", "Necropolis"),
    ("OVERGROWN_ESTATE", "Overgrown Estate"),
    ("PILLAGE", "Pillage"),
    ("POOR_HOUSE", "Poor House"),
    ("PROCESSION", "Procession"),
    ("RATS", "Rats"),
    ("REBUILD", "Rebuild"),
    ("ROGUE", "Rogue"),
    ("RUINED_LIBRARY", "Ruined Library"),
    ("RUINED_MARKET", "Ruined Market"),
    ("RUINED_VILLAGE", "Ruined Village"),
    ("SAGE", "Sage"),
    ("SCAVENGER", "Scavenger"),
    ("SIR_BAILEY", "Sir Bailey"),
    ("SIR_DESTRY", "Sir Destry"),
    ("SIR_MARTIN", "Sir Martin"),
    ("SIR_MICHAEL", "Sir Michael"),
    ("SIR_VANDER", "Sir Vander"),
    ("SPOILS", "Spoils"),
    ("STOREROOM", "Storeroom"),
    ("SQUIRE", "Squire"),
    ("SURVIVORS", "Survivors"),
    ("URCHIN", "Urchin"),
    ("VAGRANT", "Vagrant"),
    ("WANDERING_MINSTREL", "Wandering Minstrel"),
    ("ADVISOR", "Advisor"),
    ("BAKER", "Baker"),
    ("BUTCHER", "Butcher"),
    ("CANDLESTICK_MAKER", "Candlestick Maker"),
    ("DOCTOR", "Doctor"),
    ("HERALD", "Herald"),
    ("JOURNEYMAN", "Journeyman"),
    ("MASTERPIECE", "Masterpiece"),
    ("MERCHANT_GUILD", "Merchant Guild"),
    ("PLAZA", "Plaza"),
    ("TAXMAN", "Taxman"),
    ("SOOTHSAYER", "Soothsayer"),
    ("STONEMASON", "Stonemason"),
    ("ALMS", "Alms"),
    ("AMULET", "Amulet"),
    ("ARTIFICER", "Artificer"),
    ("BALL", "Ball"),
    ("BONFIRE", "Bonfire"),
    ("BORROW", "Borrow"),
    ("BRIDGE_TROLL", "Bridge Troll"),
    ("CARAVAN_GUARD", "Caravan Guard"),
    ("CHAMPION", "Champion"),
    ("COIN_OF_THE_REALM", "Coin Of The Realm"),
    ("DISCIPLE", "Disciple"),
    ("DISTANT_LANDS", "Distant Lands"),
    ("DUNGEON", "Dungeon"),
    ("DUPLICATE", "Duplicate"),
    ("EXPEDITION", "Expedition"),
    ("FERRY", "Ferry"),
    ("FUGITIVE", "Fugitive"),
    ("GEAR", "Gear"),
    ("GIANT", "Giant"),
    ("GUIDE", "Guide"),
    ("HAUNTED_WOODS", "Haunted Woods"),
    ("HERO", "Hero"),
    ("HIRELING", "Hireling"),
    ("INHERITANCE", "Inheritance"),
    ("LOST_ARTS", "Lost Arts"),
    ("LOST_CITY", "Lost City"),
    ("MAGPIE", "Magpie"),
    ("MESSENGER", "Messenger"),
    ("MISER", "Miser"),
    ("MISSION", "Mission"),
    ("PATHFINDING", "Pathfinding"),
    ("PAGE", "Page"),
    ("PEASANT", "Peasant"),
    ("PILGRIMAGE", "Pilgrimage"),
    ("PLAN", "Plan"),
    ("PORT", "Port"),
    ("QUEST", "Quest"),
    ("RANGER", "Ranger"),
    ("RAID", "Raid"),
    ("RATCATCHER", "Ratcatcher"),
    ("RAZE", "Raze"),
    ("RELIC", "Relic"),
    ("ROYAL_CARRIAGE", "Royal Carriage"),
    ("SAVE", "Save"),
    ("SCOUTING_PARTY", "Scouting Party"),
    ("SEAWAY", "Seaway"),
    ("SOLDIER", "Soldier"),
    ("STORYTELLER", "Storyteller"),
    ("SWAMP_HAG", "Swamp Hag"),
    ("TEACHER", "Teacher"),
    ("TRAVELLING_FAIR", "Travelling Fair"),
    ("TRADE", "Trade"),
    ("TRAINING", "Training"),
    ("TRANSMOGRIFY", "Transmogrify"),
    ("TREASURE_TROVE", "Treasure Trove"),
    ("TREASURE_HUNTER", "Treasure Hunter"),
    ("WARRIOR", "Warrior"),
    ("WINE_MERCHANT", "Wine Merchant"),
    ("ENCAMPMENT", "Encampment"),
    ("PLUNDER", "Plunder"),
    ("PATRICIAN", "Patrician"),
    ("EMPORIUM", "Emporium"),
    ("SETTLERS", "Settlers"),
    ("BUSTLING_VILLAGE", "Bustling Village"),
    ("CATAPULT", "Catapult"),
    ("ROCKS", "Rocks"),
    ("GLADIATOR", "Gladiator"),
    ("FORTUNE", "Fortune"),
    ("CASTLES", "Castles"),
    ("HUMBLE_CASTLE", "Humble Castle"),
    ("CRUMBLING_CASTLE", "Crumbling Castle"),
    ("SMALL_CASTLE", "Small Castle"),
    ("HAUNTED_CASTLE", "Haunted Castle"),
    ("OPULENT_CASTLE", "Opulent Castle"),
    ("SPRAWLING_CASTLE", "Sprawling Castle"),
    ("GRAND_CASTLE", "Grand Castle"),
    ("KINGS_CASTLE", "Kings Castle"),
    ("ADVANCE", "Advance"),
    ("ANNEX", "Annex"),
    ("ARCHIVE", "Archive"),
    ("AQUEDUCT", "Aqueduct"),
    ("ARENA", "Arena"),
    ("BANDIT_FORT", "Bandit Fort"),
    ("BANQUET", "Banquet"),
    ("BASILICA", "Basilica"),
    ("BATHS", "Baths"),
    ("BATTLEFIELD", "Battlefield"),
    ("CAPITAL", "Capital"),
    ("CHARM", "Charm"),
    ("CHARIOT_RACE", "Chariot Race"),
    ("CITY_QUARTER", "City Quarter"),
    ("COLONNADE", "Colonnade"),
    ("CONQUEST", "Conquest"),
    ("CROWN", "Crown"),
    ("DELVE", "Delve"),
    ("DEFILED_SHRINE", "Defiled Shrine"),
    ("DOMINATE", "Dominate"),
    ("DONATE", "Donate"),
    ("ENCHANTRESS", "Enchantress"),
    ("ENGINEER", "Engineer"),
    ("FARMERS_MARKET", "Farmers Market"),
    ("FORUM", "Forum"),
    ("FOUNTAIN", "Fountain"),
    ("GROUNDSKEEPER", "Groundskeeper"),
    ("KEEP", "Keep"),
    ("LABYRINTH", "Labyrinth"),
    ("LEGIONARY", "Legionary"),
    ("MOUNTAIN_PASS", "Mountain Pass"),
    ("MUSEUM", "Museum"),
    ("OBELISK", "Obelisk"),
    ("ORCHARD", "Orchard"),
    ("OVERLORD", "Overlord"),
    ("PALACE", "Palace"),
    ("RITUAL", "Ritual"),
    ("ROYAL_BLACKSMITH", "Royal Blacksmith"),
    ("SACRIFICE", "Sacrifice"),
    ("SALT_THE_EARTH", "Salt The Earth"),
    ("TAX", "Tax"),
    ("TEMPLE", "Temple"),
    ("TOMB", "Tomb"),
    ("TOWER", "Tower"),
    ("TRIUMPH", "Triumph"),
    ("TRIUMPHAL_ARCH", "Triumphal Arch"),
    ("VILLA", "Villa"),
    ("WALL", "Wall"),
    ("WOLF_DEN", "Wolf Den"),
    ("WEDDING", "Wedding"),
    ("WILD_HUNT", "Wild Hunt"),
    ("WINDFALL", "Windfall"),
    ("PIG", "Pig"),
    ("MINUS_CARD", "MinusCard"),
    ("MINUS_COIN", "MinusCoin"),
    ("STATE_LIMBO", "State Limbo"),
    ("DRUID_BOONS", "Druid Boons"),
    ("BOON_DRAWPILE", "Boon Drawpile"),
    ("BOON_DISCARDPILE", "Boon Discardpile"),
    ("THE_EARTHS_GIFT", "The Earths Gift"),
    ("THE_FIELDS_GIFT", "The Fields Gift"),
    ("THE_FLAMES_GIFT", "The Flames Gift"),
    ("THE_FORESTS_GIFT", "The Forests Gift"),
    ("THE_MOONS_GIFT", "The Moons Gift"),
    ("THE_MOUNTAINS_GIFT", "The Mountains Gift"),
    ("THE_RIVERS_GIFT", "The Rivers Gift"),
    ("THE_SEAS_GIFT", "The Seas Gift"),
    ("THE_SKYS_GIFT", "The Skys Gift"),
    ("THE_SUNS_GIFT", "The Suns Gift"),
    ("THE_SWAMPS_GIFT", "The Swamps Gift"),
    ("THE_WINDS_GIFT", "The Winds Gift"),
    ("HEX_DRAWPILE", "Hex Drawpile"),
    ("HEX_DISCARDPILE", "Hex Discardpile"),
    ("BAD_OMENS", "Bad Omens"),
    ("DELUSION", "Delusion"),
    ("ENVY", "Envy"),
    ("FAMINE", "Famine"),
    ("FEAR", "Fear"),
    ("GREED", "Greed"),
    ("HAUNTING", "Haunting"),
    ("LOCUSTS", "Locusts"),
    ("MISERY", "Misery"),
    ("PLAGUE", "Plague"),
    ("POVERTY", "Poverty"),
    ("WAR", "War"),
    ("MISERABLE", "Miserable"),
    ("TWICE_MISERABLE", "Twice Miserable"),
    ("ENVIOUS", "Envious"),
    ("DELUDED", "Deluded"),
    ("LOST_IN_THE_WOODS", "Lost In The Woods"),
    ("BARD", "Bard"),
    ("BLESSED_VILLAGE", "Blessed Village"),
    ("CHANGELING", "Changeling"),
    ("CEMETERY", "Cemetery"),
    ("COBBLER", "Cobbler"),
    ("CONCLAVE", "Conclave"),
    ("CRYPT", "Crypt"),
    ("CURSED_VILLAGE", "Cursed Village"),
    ("DEN_OF_SIN", "Den Of Sin"),
    ("DEVILS_WORKSHOP", "Devils Workshop"),
    ("DRUID", "Druid"),
    ("EXORCIST", "Exorcist"),
    ("FAITHFUL_HOUND", "Faithful Hound"),
    ("FOOL", "Fool"),
    ("GHOST_TOWN", "Ghost Town"),
    ("GUARDIAN", "Guardian"),
    ("IDOL", "Idol"),
    ("LEPRECHAUN", "Leprechaun"),
    ("MONASTERY", "Monastery"),
    ("NECROMANCER", "Necromancer"),
    ("NIGHT_WATCHMAN", "Night Watchman"),
    ("PIXIE", "Pixie"),
    ("POOKA", "Pooka"),
    ("RAIDER", "Raider"),
    ("SACRED_GROVE", "Sacred Grove"),
    ("SECRET_CAVE", "Secret Cave"),
    ("SHEPHERD", "Shepherd"),
    ("SKULK", "Skulk"),
    ("TORMENTOR", "Tormentor"),
    ("TRAGIC_HERO", "Tragic Hero"),
    ("TRACKER", "Tracker"),
    ("VAMPIRE", "Vampire"),
    ("WEREWOLF", "Werewolf"),
    ("CURSED_GOLD", "Cursed Gold"),
    ("GOAT", "Goat"),
    ("HAUNTED_MIRROR", "Haunted Mirror"),
    ("LUCKY_COIN", "Lucky Coin"),
    ("MAGIC_LAMP", "Magic Lamp"),
    ("PASTURE", "Pasture"),
    ("POUCH", "Pouch"),
    ("BAT", "Bat"),
    ("GHOST", "Ghost"),
    ("IMP", "Imp"),
    ("WILL_O_WISP", "Will O Wisp"),
    ("WISH", "Wish"),
    ("ZOMBIE_APPRENTICE", "Zombie Apprentice"),
    ("ZOMBIE_MASON", "Zombie Mason"),
    ("ZOMBIE_SPY", "Zombie Spy"),
    ("ACTING_TROUPE", "Acting Troupe"),
    ("BORDER_GUARD", "Border Guard"),
    ("CARGO_SHIP", "Cargo Ship"),
    ("DUCAT", "Ducat"),
    ("EXPERIMENT", "Experiment"),
    ("FLAG_BEARER", "Flag Bearer"),
    ("HIDEOUT", "Hideout"),
    ("INVENTOR", "Inventor"),
    ("IMPROVE", "Improve"),
    ("LACKEYS", "Lackeys"),
    ("MOUNTAIN_VILLAGE", "Mountain Village"),
    ("PATRON", "Patron"),
    ("PRIEST", "Priest"),
    ("RESEARCH", "Research"),
    ("SILK_MERCHANT", "Silk Merchant"),
    ("OLD_WITCH", "Old Witch"),
    ("RECRUITER", "Recruiter"),
    ("SCEPTER", "Scepter"),
    ("SCHOLAR", "Scholar"),
    ("SCULPTOR", "Sculptor"),
    ("SEER", "Seer"),
    ("SPICES", "Spices"),
    ("SWASHBUCKLER", "Swashbuckler"),
    ("TREASURER", "Treasurer"),
    ("VILLAIN", "Villain"),
    ("FLAG", "Flag"),
    ("HORN", "Horn"),
    ("KEY", "Key"),
    ("LANTERN", "Lantern"),
    ("TREASURE_CHEST", "Treasure Chest"),
    ("ACADEMY", "Academy"),
    ("BARRACKS", "Barracks"),
    ("CANAL", "Canal"),
    ("CAPITALISM", "Capitalism"),
    ("CATHEDRAL", "Cathedral"),
    ("CITADEL", "Citadel"),
    ("CITY_GATE", "City Gate"),
    ("CROP_ROTATION", "Crop Rotation"),
    ("EXPLORATION", "Exploration"),
    ("FAIR", "Fair"),
    ("FLEET", "Fleet"),
    ("GUILDHALL", "Guildhall"),
    ("INNOVATION", "Innovation"),
    ("PAGEANT", "Pageant"),
    ("PIAZZA", "Piazza"),
    ("ROAD_NETWORK", "Road Network"),
    ("SEWERS", "Sewers"),
    ("SILOS", "Silos"),
    ("SINISTER_PLOT", "Sinister Plot"),
    ("STAR_CHART", "Star Chart"),
    ("SAUNA", "Sauna"),
    ("AVANTO", "Avanto"),
    ("BLACK_MARKET", "Black Market"),
    ("ENVOY", "Envoy"),
    ("GOVERNOR", "Governor"),
    ("PRINCE", "Prince"),
    ("STASH", "Stash"),
    ("SUMMON", "Summon"),
    ("WALLED_VILLAGE", "Walled Village"),
    ("BLACK_MARKET_PILE", "Black Market Pile"),
    ("DISMANTLE", "Dismantle"),
    ("CAPTAIN", "Captain"),
    ("CHURCH", "Church"),
    ("MARCHLAND", "Marchland"),
    ("BLACK_CAT", "Black Cat"),
    ("SLEIGH", "Sleigh"),
    ("SUPPLIES", "Supplies"),
    ("CAMEL_TRAIN", "Camel Train"),
    ("GOATHERD", "Goatherd"),
    ("SCRAP", "Scrap"),
    ("SHEEPDOG", "Sheepdog"),
    ("SNOWY_VILLAGE", "Snowy Village"),
    ("STOCKPILE", "Stockpile"),
    ("BOUNTY_HUNTER", "Bounty Hunter"),
    ("CARDINAL", "Cardinal"),
    ("CAVALRY", "Cavalry"),
    ("GROOM", "Groom"),
    ("HOSTELRY", "Hostelry"),
    ("VILLAGE_GREEN", "Village Green"),
    ("BARGE", "Barge"),
    ("COVEN", "Coven"),
    ("DISPLACE", "Displace"),
    ("FALCONER", "Falconer"),
    ("FISHERMAN", "Fisherman"),
    ("GATEKEEPER", "Gatekeeper"),
    ("HUNTING_LODGE", "Hunting Lodge"),
    ("KILN", "Kiln"),
    ("LIVERY", "Livery"),
    ("MASTERMIND", "Mastermind"),
    ("PADDOCK", "Paddock"),
    ("SANCTUARY", "Sanctuary"),
    ("DESTRIER", "Destrier"),
    ("WAYFARER", "Wayfarer"),
    ("ANIMAL_FAIR", "Animal Fair"),
    ("HORSE", "Horse"),
    ("WAY_OF_THE_BUTTERFLY", "Way Of The Butterfly"),
    ("WAY_OF_THE_CAMEL", "Way Of The Camel"),
    ("WAY_OF_THE_CHAMELEON", "Way Of The Chameleon"),
    ("WAY_OF_THE_FROG", "Way Of The Frog"),
    ("WAY_OF_THE_GOAT", "Way Of The Goat"),
    ("WAY_OF_THE_HORSE", "Way Of The Horse"),
    ("WAY_OF_THE_MOLE", "Way Of The Mole"),
    ("WAY_OF_THE_MONKEY", "Way Of The Monkey"),
    ("WAY_OF_THE_MOUSE", "Way Of The Mouse"),
    ("WAY_OF_THE_MULE", "Way Of The Mule"),
    ("WAY_OF_THE_OTTER", "Way Of The Otter"),
    ("WAY_OF_THE_OWL", "Way Of The Owl"),
    ("WAY_OF_THE_OX", "Way Of The Ox"),
    ("WAY_OF_THE_PIG", "Way Of The Pig"),
    ("WAY_OF_THE_RAT", "Way Of The Rat"),
    ("WAY_OF_THE_SEAL", "Way Of The Seal"),
    ("WAY_OF_THE_SHEEP", "Way Of The Sheep"),
    ("WAY_OF_THE_SQUIRREL", "Way Of The Squirrel"),
    ("WAY_OF_THE_TURTLE", "Way Of The Turtle"),
    ("WAY_OF_THE_WORM", "Way Of The Worm"),
    ("DELAY", "Delay"),
    ("DESPERATION", "Desperation"),
    ("GAMBLE", "Gamble"),
    ("PURSUE", "Pursue"),
    ("RIDE", "Ride"),
    ("TOIL", "Toil"),
    ("ENHANCE", "Enhance"),
    ("MARCH", "March"),
    ("TRANSPORT", "Transport"),
    ("BANISH", "Banish"),
    ("BARGAIN", "Bargain"),
    ("INVEST", "Invest"),
    ("SEIZE_THE_DAY", "Seize The Day"),
    ("COMMERCE", "Commerce"),
    ("DEMAND", "Demand"),
    ("STAMPEDE", "Stampede"),
    ("REAP", "Reap"),
    ("ENCLAVE", "Enclave"),
    ("ALLIANCE", "Alliance"),
    ("POPULATE", "Populate"),
    ("CARD_OF_THE_BUTTERFLY", "Card Of The Butterfly"),
    ("CARD_OF_THE_CAMEL", "Card Of The Camel"),
    ("CARD_OF_THE_CHAMELEON", "Card Of The Chameleon"),
    ("CARD_OF_THE_FROG", "Card Of The Frog"),
    ("CARD_OF_THE_GOAT", "Card Of The Goat"),
    ("CARD_OF_THE_HORSE", "Card Of The Horse"),
    ("CARD_OF_THE_MOLE", "Card Of The Mole"),
    ("CARD_OF_THE_MONKEY", "Card Of The Monkey"),
    ("CARD_OF_THE_MOUSE", "Card Of The Mouse"),
    ("CARD_OF_THE_MULE", "Card Of The Mule"),
    ("CARD_OF_THE_OTTER", "Card Of The Otter"),
    ("CARD_OF_THE_OWL", "Card Of The Owl"),
    ("CARD_OF_THE_OX", "Card Of The Ox"),
    ("CARD_OF_THE_PIG", "Card Of The Pig"),
    ("CARD_OF_THE_RAT", "Card Of The Rat"),
    ("CARD_OF_THE_SEAL", "Card Of The Seal"),
    ("CARD_OF_THE_SHEEP", "Card Of The Sheep"),
    ("CARD_OF_THE_SQUIRREL", "Card Of The Squirrel"),
    ("CARD_OF_THE_TURTLE", "Card Of The Turtle"),
    ("CARD_OF_THE_WORM", "Card Of The Worm"),
    ("MONKEY", "Monkey"),
    ("BLOCKADE", "Blockade"),
    ("SAILOR", "Sailor"),
    ("PIRATE", "Pirate"),
    ("CORSAIR", "Corsair"),
    ("SEA_CHART", "Sea Chart"),
    ("ASTROLABE", "Astrolabe"),
    ("TIDE_POOLS", "Tide Pools"),
    ("SEA_WITCH", "Sea Witch"),
    ("ANVIL", "Anvil"),
    ("CLERK", "Clerk"),
    ("INVESTMENT", "Investment"),
    ("TIARA", "Tiara"),
    ("CHARLATAN", "Charlatan"),
    ("COLLECTION", "Collection"),
    ("CRYSTAL_BALL", "Crystal Ball"),
    ("MAGNATE", "Magnate"),
    ("WAR_CHEST", "War Chest"),
    ("GUARD_DOG", "Guard Dog"),
    ("BERSERKER", "Berserker"),
    ("NOMADS", "Nomads"),
    ("TRAIL", "Trail"),
    ("WEAVER", "Weaver"),
    ("SOUK", "Souk"),
    ("CAULDRON", "Cauldron"),
    ("WHEELWRIGHT", "Wheelwright"),
    ("WITCHS_HUT", "Witchs Hut"),
    ("UNUSED_SLOT_27", "unused"),
    ("UNUSED_SLOT_28", "unused"),
    ("UNUSED_SLOT_29", "unused"),
    ("UNUSED_SLOT_30", "unused"),
    ("UNUSED_SLOT_31", "unused"),
    ("UNUSED_SLOT_32", "unused"),
    ("UNUSED_SLOT_33", "unused"),
    ("UNUSED_SLOT_34", "unused"),
    ("UNUSED_SLOT_35", "unused"),
    ("UNUSED_SLOT_36", "unused"),
    ("UNUSED_SLOT_37", "unused"),
    ("UNUSED_SLOT_38", "unused"),
    ("UNUSED_SLOT_39", "unused"),
    ("SHOP", "Shop"),
    ("CARNIVAL", "Carnival"),
    ("FERRYMAN", "Ferryman"),
    ("TOWN", "Town"),
    ("MODIFY", "Modify"),
    ("MERCHANT_CAMP", "Merchant Camp"),
    ("SWAP", "Swap"),
    ("SKIRMISHER", "Skirmisher"),
    ("HIGHWAYMAN", "Highwayman"),
    ("BARBARIAN", "Barbarian"),
    ("INNKEEPER", "Innkeeper"),
    ("CAPITAL_CITY", "Capital City"),
    ("SPECIALIST", "Specialist"),
    ("CARPENTER", "Carpenter"),
    ("ROYAL_GALLEY", "Royal Galley"),
    ("MARQUIS", "Marquis"),
    ("SENTINEL", "Sentinel"),
    ("COURIER", "Courier"),
    ("GALLERIA", "Galleria"),
    ("HUNTER", "Hunter"),
    ("SYCOPHANT", "Sycophant"),
    ("UNDERLING", "Underling"),
    ("IMPORTER", "Importer"),
    ("CONTRACT", "Contract"),
    ("EMISSARY", "Emissary"),
    ("BAUBLE", "Bauble"),
    ("BROKER", "Broker"),
    ("GUILDMASTER", "Guildmaster"),
    ("ARCHITECTS_GUILD", "Architects Guild"),
    ("ORDER_OF_ASTROLOGERS", "Order of Astrologers"),
    ("LEAGUE_OF_BANKERS", "League of Bankers"),
    ("MOUNTAIN_FOLK", "Mountain Folk"),
    ("WOODWORKERS_GUILD", "Woodworkers Guild"),
    ("PEACEFUL_CULT", "Peaceful Cult"),
    ("CRAFTERS_GUILD", "Crafters Guild"),
    ("CAVE_DWELLERS", "Cave Dwellers"),
    ("PLATEAU_SHEPHERDS", "Plateau Shepherds"),
    ("DESERT_GUIDES", "Desert Guides"),
    ("FAMILY_OF_INVENTORS", "Family of Inventors"),
    ("ISLAND_FOLK", "Island Folk"),
    ("ORDER_OF_MASONS", "Order of Masons"),
    ("BAND_OF_NOMADS", "Band of Nomads"),
    ("GANG_OF_PICKPOCKETS", "Gang of Pickpockets"),
    ("MARKET_TOWNS", "Market Towns"),
    ("FOREST_DWELLERS", "Forest Dwellers"),
    ("FELLOWSHIP_OF_SCRIBES", "Fellowship of Scribes"),
    ("LEAGUE_OF_SHOPKEEPERS", "League of Shopkeepers"),
    ("COASTAL_HAVEN", "Coastal Haven"),
    ("CITY_STATE", "City-state"),
    ("TRAPPERS_LODGE", "Trappers Lodge"),
    ("CIRCLE_OF_WITCHES", "Circle of Witches"),
    ("AUGUR_PILE", "Augur Pile"),
    ("HERB_GATHERER", "Herb Gatherer"),
    ("ACOLYTE", "Acolyte"),
    ("SORCERESS", "Sorceress"),
    ("SIBYL", "Sibyl"),
    ("CLASH_PILE", "Clash Pile"),
    ("BATTLE_PLAN", "Battle Plan"),
    ("ARCHER", "Archer"),
    ("WARLORD", "Warlord"),
    ("TERRITORY", "Territory"),
    ("FORT_PILE", "Fort Pile"),
    ("TENT", "Tent"),
    ("GARRISON", "Garrison"),
    ("HILL_FORT", "Hill Fort"),
    ("STRONGHOLD", "Stronghold"),
    ("ODYSSEY_PILE", "Odyssey Pile"),
    ("OLD_MAP", "Old Map"),
    ("VOYAGE", "Voyage"),
    ("SUNKEN_TREASURE", "Sunken Treasure"),
    ("DISTANT_SHORE", "Distant Shore"),
    ("TOWNSFOLK_PILE", "Townsfolk Pile"),
    ("TOWN_CRIER", "Town Crier"),
    ("BLACKSMITH", "Blacksmith"),
    ("MILLER", "Miller"),
    ("ELDER", "Elder"),
    ("WIZARD_PILE", "Wizard Pile"),
    ("STUDENT", "Student"),
    ("CONJURER", "Conjurer"),
    ("SORCERER", "Sorcerer"),
    ("LICH", "Lich"),
    ("CHARLATAN_CURSE", "Charlatan Curse"),
    ("CAGE", "Cage"),
    ("GROTTO", "Grotto"),
    ("JEWELLED_EGG", "Jewelled Egg"),
    ("SEARCH", "Search"),
    ("SHAMAN", "Shaman"),
    ("SECLUDED_SHRINE", "Secluded Shrine"),
    ("SIREN", "Siren"),
    ("STOWAWAY", "Stowaway"),
    ("TASKMASTER", "Taskmaster"),
    ("ABUNDANCE", "Abundance"),
    ("CABIN_BOY", "Cabin Boy"),
    ("CRUCIBLE", "Crucible"),
    ("FLAGSHIP", "Flagship"),
    ("FORTUNE_HUNTER", "Fortune Hunter"),
    ("GONDOLA", "Gondola"),
    ("HARBOR_VILLAGE", "Harbor Village"),
    ("LANDING_PARTY", "Landing Party"),
    ("MAPMAKER", "Mapmaker"),
    ("MAROON", "Maroon"),
    ("ROPE", "Rope"),
    ("SWAMP_SHACKS", "Swamp Shacks"),
    ("TOOLS", "Tools"),
    ("BURIED_TREASURE", "Buried Treasure"),
    ("CREW", "Crew"),
    ("CUTTHROAT", "Cutthroat"),
    ("ENLARGE", "Enlarge"),
    ("FIGURINE", "Figurine"),
    ("FIRST_MATE", "First Mate"),
    ("FRIGATE", "Frigate"),
    ("LONGSHIP", "Longship"),
    ("MINING_ROAD", "Mining Road"),
    ("PENDANT", "Pendant"),
    ("PICKAXE", "Pickaxe"),
    ("PILGRIM", "Pilgrim"),
    ("QUARTERMASTER", "Quartermaster"),
    ("SILVER_MINE", "Silver Mine"),
    ("TRICKSTER", "Trickster"),
    ("WEALTHY_VILLAGE", "Wealthy Village"),
    ("SACK_OF_LOOT", "Sack of Loot"),
    ("KINGS_CACHE", "King's Cache"),
    ("BURY", "Bury"),
    ("AVOID", "Avoid"),
    ("DELIVER", "Deliver"),
    ("PERIL", "Peril"),
    ("RUSH", "Rush"),
    ("FORAY", "Foray"),
    ("LAUNCH", "Launch"),
    ("MIRROR", "Mirror"),
    ("PREPARE", "Prepare"),
    ("SCROUNGE", "Scrounge"),
    ("JOURNEY", "Journey"),
    ("MAELSTROM", "Maelstrom"),
    ("LOOTING", "Looting"),
    ("INVASION", "Invasion"),
    ("PROSPER", "Prosper"),
    ("LOOT_PILE", "Loot Pile"),
    ("AMPHORA", "Amphora"),
    ("DOUBLOONS", "Doubloons"),
    ("ENDLESS_CHALICE", "Endless Chalice"),
    ("FIGUREHEAD", "Figurehead"),
    ("HAMMER", "Hammer"),
    ("INSIGNIA", "Insignia"),
    ("JEWELS", "Jewels"),
    ("ORB", "Orb"),
    ("PRIZE_GOAT", "Prize Goat"),
    ("PUZZLE_BOX", "Puzzle Box"),
    ("SEXTANT", "Sextant"),
    ("SHIELD", "Shield"),
    ("SPELL_SCROLL", "Spell Scroll"),
    ("STAFF", "Staff"),
    ("SWORD", "Sword"),
    ("CHEAP", "Cheap"),
    ("CURSED", "Cursed"),
    ("FATED", "Fated"),
    ("FAWNING", "Fawning"),
    ("FRIENDLY", "Friendly"),
    ("HASTY", "Hasty"),
    ("INHERITED", "Inherited"),
    ("INSPIRING", "Inspiring"),
    ("NEARBY", "Nearby"),
    ("PATIENT", "Patient"),
    ("PIOUS", "Pious"),
    ("RECKLESS", "Reckless"),
    ("RICH", "Rich"),
    ("SHY", "Shy"),
    ("TIRELESS", "Tireless"),
    ("FARMHANDS", "Farmhands"),
    ("JOUST", "Joust"),
    ("REWARDS_PILE", "Rewards Pile"),
    ("COURSER", "Courser"),
    ("RENOWN", "Renown"),
    ("CORONET", "Coronet"),
    ("DEMESNE", "Demesne"),
    ("HOUSECARL", "Housecarl"),
    ("HUGE_TURNIP", "Huge Turnip"),
    ("FARRIER", "Farrier"),
    ("INFIRMARY", "Infirmary"),
    ("FOOTPAD", "Footpad"),
    ("FISHMONGER", "Fishmonger"),
    ("SNAKE_WITCH", "Snake Witch"),
    ("ARISTOCRAT", "Aristocrat"),
    ("CRAFTSMAN", "Craftsman"),
    ("RIVERBOAT", "Riverboat"),
    ("ROOT_CELLAR", "Root Cellar"),
    ("ALLEY", "Alley"),
    ("CHANGE", "Change"),
    ("NINJA", "Ninja"),
    ("POET", "Poet"),
    ("RIVER_SHRINE", "River Shrine"),
    ("RUSTIC_VILLAGE", "Rustic Village"),
    ("GOLD_MINE", "Gold Mine"),
    ("IMPERIAL_ENVOY", "Imperial Envoy"),
    ("KITSUNE", "Kitsune"),
    ("LITTER", "Litter"),
    ("RICE_BROKER", "Rice Broker"),
    ("RONIN", "Ronin"),
    ("TANUKI", "Tanuki"),
    ("TEA_HOUSE", "Tea House"),
    ("SAMURAI", "Samurai"),
    ("RICE", "Rice"),
    ("MOUNTAIN_SHRINE", "Mountain Shrine"),
    ("DAIMYO", "Daimyo"),
    ("ARTIST", "Artist"),
    ("APPROACHING_ARMY", "Approaching Army"),
    ("BIDING_TIME", "Biding Time"),
    ("BUREAUCRACY", "Bureaucracy"),
    ("DIVINE_WIND", "Divine Wind"),
    ("ENLIGHTENMENT", "Enlightenment"),
    ("FLOURISHING_TRADE", "Flourishing Trade"),
    ("GOOD_HARVEST", "Good Harvest"),
    ("GREAT_LEADER", "Great Leader"),
    ("GROWTH", "Growth"),
    ("HARSH_WINTER", "Harsh Winter"),
    ("KIND_EMPEROR", "Kind Emperor"),
    ("PANIC", "Panic"),
    ("PROGRESS", "Progress"),
    ("RAPID_EXPANSION", "Rapid Expansion"),
    ("SICKNESS", "Sickness"),
    ("AMASS", "Amass"),
    ("ASCETICISM", "Asceticism"),
    ("CREDIT", "Credit"),
    ("FORESIGHT", "Foresight"),
    ("KINTSUGI", "Kintsugi"),
    ("PRACTICE", "Practice"),
    ("SEA_TRADE", "Sea Trade"),
    ("RECEIVE_TRIBUTE", "Receive Tribute"),
    ("GATHER", "Gather"),
    ("CONTINUE", "Continue"),
)

CARD_SYMBOLS: tuple[str, ...] = tuple(symbol for symbol, _ in CARD_TABLE)
CARD_NAMES: tuple[str, ...] = tuple(name for _, name in CARD_TABLE)

CardId = IntEnum(
    "CardId",
    {symbol: ordinal for ordinal, symbol in enumerate(CARD_SYMBOLS)},
    module=__name__,
)

_NAME_ORDINALS: dict[str, list[int]] = {}
for _ordinal, _name in enumerate(CARD_NAMES):
    _NAME_ORDINALS.setdefault(_name, []).append(_ordinal)

CARD_ID_BY_NAME: dict[str, CardId] = {
    name: CardId(ordinals[0])
    for name, ordinals in _NAME_ORDINALS.items()
    if len(ordinals) == 1
}


def card_name(wire_id: int) -> str:
    """Return the display name for a card wire ordinal."""
    if not 0 <= wire_id < len(CARD_NAMES):
        raise ValueError(f"unknown card wire id {wire_id}")
    return CARD_NAMES[wire_id]


def card_symbol(wire_id: int) -> str:
    """Return the unique bundle symbol for a card wire ordinal."""
    if not 0 <= wire_id < len(CARD_SYMBOLS):
        raise ValueError(f"unknown card wire id {wire_id}")
    return CARD_SYMBOLS[wire_id]


def card_id(name: str) -> CardId:
    """Return a wire ordinal from an unambiguous display name or symbol."""
    if name in CardId.__members__:
        return CardId[name]
    ordinals = _NAME_ORDINALS.get(name)
    if not ordinals:
        raise ValueError(f"unknown card name {name!r}")
    if len(ordinals) != 1:
        raise ValueError(
            f"ambiguous card name {name!r}; use one of "
            + ", ".join(CARD_SYMBOLS[index] for index in ordinals)
        )
    return CardId(ordinals[0])
